export const SWAGGER_COOKIE_TOKEN_KEY = 'swagger_token'
export const REDIRECT_TO_LOGIN = '/login-api'
export const ENTRY_POINT_PROTECT = '/api/json'
export const SWAGGER_PROTECT_MODULE_ID = 'SwaggerProtectId'
export const SWAGGER_PROTECT_OPTIONS = 'SWAGGER_PROTECT_OPTIONS'
